### ISSUE TITLE
Sync issue between PR and bpo issue

### ISSUE THREAD

**Issue by matrixise** [python/bugs.python.org#17]
This PR is merged into CPython master https://github.com/python/cpython/pull/8453

but this PR is not marked as 'merged' in https://bugs.python.org/issue34217

Any idea?

Thank you

**Comment by terryjreedy** [comment]
The bots are not perfect.  I believe this happened to me once and when closing, I added a note that PR nnnn had been merged in spite of the absence of 'merged'.

That said, the reference PR is *now* listed as 'merged'.  Perhaps the reference here, noted on the PR, poked our bot into action ;-).

**Comment by ezio-melotti** [comment]
Yes, as far as I know, if an error occurs or if the bot can't contact bpo for whatever reason, the bot is not going to automatically try again, but will report the issue on the admin interface and allow an admin to re-send the payload manually.  This is most likely what happened, and since the PRs are marked as merged now, I'm going to close this issue.

**Comment by serhiy-storchaka** [comment]
I have updated the status of the reference manually.
