### ISSUE TITLE
Add X-Roundup-issue-number when send an email

### ISSUE THREAD

**Issue by matrixise** [python/bugs.python.org#36]
Because I would like to sort my incoming emails or follow an issue, I need to search on the subject field. I would like to propose a new header for the email, just the number of the issue. Do you think it is possible? 

I don't know where the repository is, but maybe I could submit a patch.

Thank you

**Comment by rouilj** [comment]
This is currently configured in the code. Specifically roundupdb.py in send_message. Search for X-Roundup. This would be good to add upstream. I am actually surprised it's not there already.
Opened: https://issues.roundup-tracker.org/issue2551043

However I suggest X-Roundup-issue-id rather than number. The field that holds the number is id, so this makes sure that the header name won't collide with a new "number" field.

**Comment by rouilj** [comment]
FYI, this feature has been added upstream. See https://issues.roundup-tracker.org/issue2551043 for
details on X-Roundup-Issue-Id: id# header. It still needs to be applied on bpo.

**Comment by berkerpeksag** [comment]
The upstream feature has been released in Roundup 2.0. We are going to get it for free when we ditch out fork. Closing this for now.
